/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.blog.statistics.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BlogStatistic service. Represents a row in the &quot;BlogStats_BlogStatistic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.blog.statistics.model.impl.BlogStatisticModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.blog.statistics.model.impl.BlogStatisticImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlogStatistic
 * @generated
 */
@ProviderType
public interface BlogStatisticModel
	extends BaseModel<BlogStatistic>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a blog statistic model instance should use the {@link BlogStatistic} interface instead.
	 */

	/**
	 * Returns the primary key of this blog statistic.
	 *
	 * @return the primary key of this blog statistic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this blog statistic.
	 *
	 * @param primaryKey the primary key of this blog statistic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the blog statistic ID of this blog statistic.
	 *
	 * @return the blog statistic ID of this blog statistic
	 */
	public long getBlogStatisticId();

	/**
	 * Sets the blog statistic ID of this blog statistic.
	 *
	 * @param blogStatisticId the blog statistic ID of this blog statistic
	 */
	public void setBlogStatisticId(long blogStatisticId);

	/**
	 * Returns the group ID of this blog statistic.
	 *
	 * @return the group ID of this blog statistic
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this blog statistic.
	 *
	 * @param groupId the group ID of this blog statistic
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this blog statistic.
	 *
	 * @return the company ID of this blog statistic
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this blog statistic.
	 *
	 * @param companyId the company ID of this blog statistic
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this blog statistic.
	 *
	 * @return the create date of this blog statistic
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this blog statistic.
	 *
	 * @param createDate the create date of this blog statistic
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this blog statistic.
	 *
	 * @return the modified date of this blog statistic
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this blog statistic.
	 *
	 * @param modifiedDate the modified date of this blog statistic
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the blogs entry ID of this blog statistic.
	 *
	 * @return the blogs entry ID of this blog statistic
	 */
	public long getBlogsEntryId();

	/**
	 * Sets the blogs entry ID of this blog statistic.
	 *
	 * @param blogsEntryId the blogs entry ID of this blog statistic
	 */
	public void setBlogsEntryId(long blogsEntryId);

	/**
	 * Returns the view count of this blog statistic.
	 *
	 * @return the view count of this blog statistic
	 */
	public long getViewCount();

	/**
	 * Sets the view count of this blog statistic.
	 *
	 * @param viewCount the view count of this blog statistic
	 */
	public void setViewCount(long viewCount);

}
// LIFERAY-SERVICE-BUILDER-HASH:1956498206