/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.blog.statistics.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.blog.statistics.model.BlogStatistic;
import com.liferay.training.blog.statistics.model.BlogStatisticModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BlogStatistic service. Represents a row in the &quot;BlogStats_BlogStatistic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BlogStatisticModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlogStatisticImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlogStatisticImpl
 * @generated
 */
public class BlogStatisticModelImpl
	extends BaseModelImpl<BlogStatistic> implements BlogStatisticModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blog statistic model instance should use the <code>BlogStatistic</code> interface instead.
	 */
	public static final String TABLE_NAME = "BlogStats_BlogStatistic";

	public static final Object[][] TABLE_COLUMNS = {
		{"blogStatisticId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"blogsEntryId", Types.BIGINT},
		{"viewCount", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("blogStatisticId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("blogsEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("viewCount", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BlogStats_BlogStatistic (blogStatisticId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,blogsEntryId LONG,viewCount LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BlogStats_BlogStatistic";

	public static final String ENTITY_ALIAS = "blogStatistic";

	public static final String ORDER_BY_JPQL =
		" ORDER BY blogStatistic.viewCount DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BlogStats_BlogStatistic.viewCount DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BLOGSENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VIEWCOUNT_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BlogStatisticModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _blogStatisticId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBlogStatisticId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _blogStatisticId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BlogStatistic.class;
	}

	@Override
	public String getModelClassName() {
		return BlogStatistic.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BlogStatistic, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BlogStatistic, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlogStatistic, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BlogStatistic)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BlogStatistic, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BlogStatistic, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BlogStatistic)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BlogStatistic, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BlogStatistic, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BlogStatistic, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<BlogStatistic, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<BlogStatistic, Object>>();

		attributeGetterFunctions.put(
			"blogStatisticId", BlogStatistic::getBlogStatisticId);
		attributeGetterFunctions.put("groupId", BlogStatistic::getGroupId);
		attributeGetterFunctions.put("companyId", BlogStatistic::getCompanyId);
		attributeGetterFunctions.put(
			"createDate", BlogStatistic::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", BlogStatistic::getModifiedDate);
		attributeGetterFunctions.put(
			"blogsEntryId", BlogStatistic::getBlogsEntryId);
		attributeGetterFunctions.put("viewCount", BlogStatistic::getViewCount);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<BlogStatistic, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<BlogStatistic, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<BlogStatistic, ?>>();

		attributeSetterBiConsumers.put(
			"blogStatisticId",
			(BiConsumer<BlogStatistic, Long>)BlogStatistic::setBlogStatisticId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<BlogStatistic, Long>)BlogStatistic::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<BlogStatistic, Long>)BlogStatistic::setCompanyId);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<BlogStatistic, Date>)BlogStatistic::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<BlogStatistic, Date>)BlogStatistic::setModifiedDate);
		attributeSetterBiConsumers.put(
			"blogsEntryId",
			(BiConsumer<BlogStatistic, Long>)BlogStatistic::setBlogsEntryId);
		attributeSetterBiConsumers.put(
			"viewCount",
			(BiConsumer<BlogStatistic, Long>)BlogStatistic::setViewCount);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getBlogStatisticId() {
		return _blogStatisticId;
	}

	@Override
	public void setBlogStatisticId(long blogStatisticId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blogStatisticId = blogStatisticId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getBlogsEntryId() {
		return _blogsEntryId;
	}

	@Override
	public void setBlogsEntryId(long blogsEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blogsEntryId = blogsEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBlogsEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("blogsEntryId"));
	}

	@Override
	public long getViewCount() {
		return _viewCount;
	}

	@Override
	public void setViewCount(long viewCount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_viewCount = viewCount;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalViewCount() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("viewCount"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BlogStatistic.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BlogStatistic toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BlogStatistic>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BlogStatisticImpl blogStatisticImpl = new BlogStatisticImpl();

		blogStatisticImpl.setBlogStatisticId(getBlogStatisticId());
		blogStatisticImpl.setGroupId(getGroupId());
		blogStatisticImpl.setCompanyId(getCompanyId());
		blogStatisticImpl.setCreateDate(getCreateDate());
		blogStatisticImpl.setModifiedDate(getModifiedDate());
		blogStatisticImpl.setBlogsEntryId(getBlogsEntryId());
		blogStatisticImpl.setViewCount(getViewCount());

		blogStatisticImpl.resetOriginalValues();

		return blogStatisticImpl;
	}

	@Override
	public int compareTo(BlogStatistic blogStatistic) {
		int value = 0;

		if (getViewCount() < blogStatistic.getViewCount()) {
			value = -1;
		}
		else if (getViewCount() > blogStatistic.getViewCount()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BlogStatistic)) {
			return false;
		}

		BlogStatistic blogStatistic = (BlogStatistic)object;

		long primaryKey = blogStatistic.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BlogStatistic> toCacheModel() {
		BlogStatisticCacheModel blogStatisticCacheModel =
			new BlogStatisticCacheModel();

		blogStatisticCacheModel.blogStatisticId = getBlogStatisticId();

		blogStatisticCacheModel.groupId = getGroupId();

		blogStatisticCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			blogStatisticCacheModel.createDate = createDate.getTime();
		}
		else {
			blogStatisticCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			blogStatisticCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			blogStatisticCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		blogStatisticCacheModel.blogsEntryId = getBlogsEntryId();

		blogStatisticCacheModel.viewCount = getViewCount();

		return blogStatisticCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BlogStatistic, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BlogStatistic, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlogStatistic, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BlogStatistic)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BlogStatistic, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BlogStatistic, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlogStatistic, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BlogStatistic)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BlogStatistic>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BlogStatistic.class, ModelWrapper.class);

	}

	private long _blogStatisticId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _blogsEntryId;
	private long _viewCount;

	public <T> T getColumnValue(String columnName) {
		Function<BlogStatistic, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BlogStatistic)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("blogStatisticId", _blogStatisticId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("blogsEntryId", _blogsEntryId);
		_columnOriginalValues.put("viewCount", _viewCount);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("blogStatisticId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("blogsEntryId", 32L);

		columnBitmasks.put("viewCount", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BlogStatistic _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-843813107