/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.blog.statistics.model.impl;

import com.liferay.training.blog.statistics.model.BlogStatistic;
import com.liferay.training.blog.statistics.service.BlogStatisticLocalServiceUtil;

/**
 * The extended model base implementation for the BlogStatistic service. Represents a row in the &quot;BlogStats_BlogStatistic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlogStatisticImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlogStatisticImpl
 * @see BlogStatistic
 * @generated
 */
public abstract class BlogStatisticBaseImpl
	extends BlogStatisticModelImpl implements BlogStatistic {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blog statistic model instance should use the <code>BlogStatistic</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BlogStatisticLocalServiceUtil.addBlogStatistic(this);
		}
		else {
			BlogStatisticLocalServiceUtil.updateBlogStatistic(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1272406970