dependencies {
	api project(":modules:blog-statistics:blog-statistics-api")

	compileOnly group: "com.liferay.portal", name: "release.portal.api"
}

buildService {
	apiDir = "../blog-statistics-api/src/main/java"
	testDir = "../blog-statistics-test/src/testIntegration/java"
}

group = "com.liferay.training.blog.statistics"